I'm sorry, but an uncaught exception occurred.

While running game code:
<<<<<<< HEAD
  File "game/script.rpy", line 135, in script
    z "For you, this I speak true."
IOError: Couldn't find file 'zecoraline11.mp3'.
=======
  File "game/script.rpy", line 74, in script
    "I hear a crashing and stomping through the brush."
IOError: Couldn't find file 'audio/sound/hoofsteps.mp3'.
>>>>>>> pr/1

-- Full Traceback ------------------------------------------------------------

Full traceback:
<<<<<<< HEAD
  File "game/script.rpy", line 135, in script
    z "For you, this I speak true."
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 708, in execute
=======
  File "game/script.rpy", line 74, in script
    "I hear a crashing and stomping through the brush."
  File "C:\Users\Nemm\Downloads\renpy-7.3.5-sdk\renpy\ast.py", line 708, in execute
>>>>>>> pr/1
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Nemm\Downloads\renpy-7.3.5-sdk\renpy\exports.py", line 1345, in say
    who(what, *args, **kwargs)
  File "C:\Users\Nemm\Downloads\renpy-7.3.5-sdk\renpy\character.py", line 1142, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "C:\Users\Nemm\Downloads\renpy-7.3.5-sdk\renpy\character.py", line 842, in do_display
    **display_args)
  File "C:\Users\Nemm\Downloads\renpy-7.3.5-sdk\renpy\character.py", line 591, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\Nemm\Downloads\renpy-7.3.5-sdk\renpy\ui.py", line 297, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\Nemm\Downloads\renpy-7.3.5-sdk\renpy\display\core.py", line 2702, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
<<<<<<< HEAD
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\display\core.py", line 3380, in interact_core
    renpy.audio.audio.periodic()
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\audio\audio.py", line 1060, in periodic
    six.reraise(exc[0], exc[1], exc[2])
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\audio\audio.py", line 1038, in periodic_thread_main
    periodic_pass()
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\audio\audio.py", line 979, in periodic_pass
    c.periodic()
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\audio\audio.py", line 457, in periodic
    topf = load(self.file_prefix + filename + self.file_suffix)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\audio\audio.py", line 73, in load
    rv = renpy.loader.load(fn)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\loader.py", line 576, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'zecoraline11.mp3'.
=======
  File "C:\Users\Nemm\Downloads\renpy-7.3.5-sdk\renpy\display\core.py", line 3380, in interact_core
    renpy.audio.audio.periodic()
  File "C:\Users\Nemm\Downloads\renpy-7.3.5-sdk\renpy\audio\audio.py", line 1060, in periodic
    six.reraise(exc[0], exc[1], exc[2])
  File "C:\Users\Nemm\Downloads\renpy-7.3.5-sdk\renpy\audio\audio.py", line 1038, in periodic_thread_main
    periodic_pass()
  File "C:\Users\Nemm\Downloads\renpy-7.3.5-sdk\renpy\audio\audio.py", line 979, in periodic_pass
    c.periodic()
  File "C:\Users\Nemm\Downloads\renpy-7.3.5-sdk\renpy\audio\audio.py", line 457, in periodic
    topf = load(self.file_prefix + filename + self.file_suffix)
  File "C:\Users\Nemm\Downloads\renpy-7.3.5-sdk\renpy\audio\audio.py", line 73, in load
    rv = renpy.loader.load(fn)
  File "C:\Users\Nemm\Downloads\renpy-7.3.5-sdk\renpy\loader.py", line 576, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'audio/sound/hoofsteps.mp3'.
>>>>>>> pr/1

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Pastel Dreams 0.222
<<<<<<< HEAD
Thu Nov 19 19:13:08 2020
=======
Thu Nov 19 17:13:24 2020
>>>>>>> pr/1
